### ISSUE TITLE
How long should it take to get the right token?

### ISSUE THREAD

**Issue by SusImpostor92839** [NAOYY/Discord-Token-Brute-Force#2]
The title says it all, how long should it take to get the right token? Oh and also, does it check tokens?

**Comment by markthetechnoob** [comment]
it worked for you>??? all i got is incorrect token passed and a bunch of other giberish

**Comment by m-Phoenix852** [comment]
> The title says it all, how long should it take to get the right token? Oh and also, does it check tokens?

You wont live long enough to brute the user ;)

Its brute forcing the token, just generating random tokens for 10 years will hardly give you a valid token, and its generating random tokens and checking against the user. Not gonna work.

**Comment by SusImpostor92839** [comment]
ok...
